### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by alerodriguezn** [Angel-Concha-Layme/Fake-Store-API#1]
Server Caído :/
![image](https://github.com/Angel-Concha-Layme/Fake-Store-API/assets/102389472/5927db61-5348-48ed-ab7c-a1878774e952)

**Comment by Angel-Concha-Layme** [comment]
I fix it soon, you could add a contributing.md to make the project a little bigger.

**Comment by Angel-Concha-Layme** [comment]
new url: https://fake-store-api-2no73ornoa-uc.a.run.app
