### ISSUE TITLE
????????? https://fakeapi.platzi.com/

### ISSUE THREAD

**Issue by WaspZix** [Angel-Concha-Layme/Fake-Store-API#3]
https://fakeapi.platzi.com/ https://fakeapi.platzi.com/ https://fakeapi.platzi.com/ https://fakeapi.platzi.com/ https://fakeapi.platzi.com/  ?????? XDXD???X?D?D?X??XD?D?D https://fakeapi.platzi.com/ https://fakeapi.platzi.com/ https://fakeapi.platzi.com/ https://fakeapi.platzi.com/ https://fakeapi.platzi.com/ https://fakeapi.platzi.com/ https://fakeapi.platzi.com/

**Comment by Angel-Concha-Layme** [comment]
If you check just a little bit the implementation, you can realize that it is quite different, the fact that the documentation looks the same is because we use the same astro template. Greetings clown
